modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/end-teleporters/issues"
[[mods]]
modId="endteleporters"
version="1.1.0" #mandatory
displayName="End Teleporters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/end-teleporters"
credits="Markus1002"
authors="Markus1002"
description='''This mod adds a way to travel vast distances using a teleporter.'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
